# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tabla_tablita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablita',
            old_name='ciudad',
            new_name='pais',
        ),
    ]
